//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongBoKhoaHoc.UserControl {
    
    
    public partial class UcThongTinChungGiangVien {
        
        /// <summary>
        /// LyLichKhoaHoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.LyLichKhoaHoc LyLichKhoaHoc;
        
        /// <summary>
        /// UcQuaTrinhGiangDayVaCongTac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcQuaTrinhGiangDayVaCongTac UcQuaTrinhGiangDayVaCongTac;
        
        /// <summary>
        /// UcDeTaiCongTrinhKhoaHoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcDeTaiCongTrinhKhoaHoc UcDeTaiCongTrinhKhoaHoc;
        
        /// <summary>
        /// UcBaiBaoKhoaHoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcBaiBaoKhoaHoc UcBaiBaoKhoaHoc;
        
        /// <summary>
        /// UcSachVaGiaoTrinh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcSachVaGiaoTrinh UcSachVaGiaoTrinh;
        
        /// <summary>
        /// UcGiaiThuongKhoaHoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcGiaiThuongKhoaHoc UcGiaiThuongKhoaHoc;
        
        /// <summary>
        /// UcKhenThuong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyCongBoKhoaHoc.UserControl.UcKhenThuong UcKhenThuong;
    }
}
